Repository 6pleasant-MBTITalk/MBTI_Talk, pull requests merged in 2023-11, with the labels that each got.

#69 feature/postFragment
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/post/PostAdapter.kt
  app/src/main/java/com/example/mbti_talk/post/PostDetailActivity.kt
  app/src/main/java/com/example/mbti_talk/post/PostFragment.kt
  app/src/main/java/com/example/mbti_talk/post/PostWriteActivity.kt
  app/src/main/res/drawable/ic_add_post_off.png
  app/src/main/res/drawable/ic_add_post_on.png
  app/src/main/res/drawable/ic_add_post_write.xml
  app/src/main/res/layout/activity_post_list.xml
Labels: FEAT

#70 [FIX]Chat
  app/src/main/java/com/example/mbti_talk/Chat/ChatRoomActivity.kt
  app/src/main/java/com/example/mbti_talk/Chat/RecyclerChatRoomsAdapter.kt
  app/src/main/java/com/example/mbti_talk/Chat/RecyclerMessagesAdapter.kt
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/res/layout/list_talk_item_mine.xml
  app/src/main/res/layout/list_talk_item_others.xml
Labels: FIX

#71 MBTI folder, BottomActivity-page
  .idea/.name
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/MBTI/MbtiResultActivity.kt
  app/src/main/java/com/example/mbti_talk/MBTI/MbtiTestActivity.kt
  app/src/main/java/com/example/mbti_talk/MBTI/MbtiquestFragment.kt
  app/src/main/java/com/example/mbti_talk/MBTI/ViewPagerAdapter.kt
  app/src/main/java/com/example/mbti_talk/Main/BottomActivity.kt
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
  app/src/main/res/layout/activity_mbti_quest.xml
  app/src/main/res/layout/activity_mbti_result.xml
  app/src/main/res/layout/activity_mbti_test.xml
  app/src/main/res/layout/activity_post_list.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, FIX

#72 LogIn-page
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/SignUpActivity2.kt
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_sign_up2.xml
Labels: FIX

#74 Feat/doyeon
  app/build.gradle.kts
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/MBTI/MbtiActivity.kt
  app/src/main/java/com/example/mbti_talk/Main/FilterDialogFragment.kt
  app/src/main/java/com/example/mbti_talk/Mbti.kt
  app/src/main/java/com/example/mbti_talk/UserData.kt
  app/src/main/java/com/example/mbti_talk/utils/Utils.kt
  app/src/main/res/drawable/chip_checked.xml
  app/src/main/res/layout/fragment_dialog_filter.xml
  app/src/main/res/layout/fragment_friend_find.xml
  app/src/main/res/values/array.xml
  app/src/main/res/values/colors.xml
Labels: FEAT

#81 MbtiResultActivity-page
  app/src/main/java/com/example/mbti_talk/MBTI/MbtiResultActivity.kt
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
  app/src/main/res/layout/activity_mbti_result.xml
  app/src/main/res/layout/fragment_my_profile.xml
Labels: FEAT, FIX

#82 Feat/doyeon
  app/src/main/java/com/example/mbti_talk/Adapter/UserAdapter.kt
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/java/com/example/mbti_talk/FriendList/FriendListFragment.kt
  app/src/main/java/com/example/mbti_talk/MBTI/Mbti.kt
  app/src/main/java/com/example/mbti_talk/utils/Utils.kt
  app/src/main/res/drawable/bad_icon.png
  app/src/main/res/drawable/good_icon.png
  app/src/main/res/drawable/perfect_icon.png
  app/src/main/res/drawable/soso_icon.png
  app/src/main/res/layout/friend_list.xml
  app/src/main/res/layout/user_list.xml
Labels: FEAT

#83 Friend-Adapter, Fragment_dialog_filter
  app/src/main/java/com/example/mbti_talk/Adapter/FriendAdapter.kt
  app/src/main/res/layout/fragment_dialog_filter.xml
Labels: FIX

#84 ChatFragment-page
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/mbti_talk/Chat/ChatFragment.kt
  app/src/main/java/com/example/mbti_talk/Chat/RecyclerChatRoomsAdapter.kt
  app/src/main/java/com/example/mbti_talk/Chat/RecyclerMessagesAdapter.kt
  app/src/main/res/drawable/chat_edge.xml
  app/src/main/res/layout/activity_chat_room.xml
  app/src/main/res/layout/list_chatroom_item.xml
  app/src/main/res/layout/list_talk_item_mine.xml
  app/src/main/res/layout/list_talk_item_others.xml
Labels: UI, FEAT, FIX

#85 MbtiResultActivity-page
  app/src/main/java/com/example/mbti_talk/MBTI/MbtiResultActivity.kt
  app/src/main/java/com/example/mbti_talk/MBTI/MbtiquestFragment.kt
  app/src/main/java/com/example/mbti_talk/Main/BottomActivity.kt
  app/src/main/res/layout/activity_chat_room.xml
  app/src/main/res/layout/activity_mbti_quest.xml
  app/src/main/res/values/strings.xml
Labels: FEAT

#91 UI/user list
  app/src/main/res/layout/user_list.xml
Labels: UI, FIX

#94 postFragment-page
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/mbti_talk/MBTI/MbtiDialogChoice.kt
  app/src/main/java/com/example/mbti_talk/MBTI/MbtiResultActivity.kt
  app/src/main/java/com/example/mbti_talk/MBTI/MbtiquestFragment.kt
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
  app/src/main/java/com/example/mbti_talk/post/PostAdapter.kt
  app/src/main/java/com/example/mbti_talk/post/PostFragment.kt
  app/src/main/java/com/example/mbti_talk/post/PostWriteActivity.kt
  app/src/main/res/drawable/ic_enfj.png
  app/src/main/res/drawable/ic_enfp.png
  app/src/main/res/drawable/ic_entj.png
  app/src/main/res/drawable/ic_entp.png
  app/src/main/res/drawable/ic_esfj.png
  app/src/main/res/drawable/ic_esfp.png
  app/src/main/res/drawable/ic_estj.png
  app/src/main/res/drawable/ic_estp.png
  app/src/main/res/drawable/ic_infj.png
  app/src/main/res/drawable/ic_infp.png
  app/src/main/res/drawable/ic_intj.png
  app/src/main/res/drawable/ic_intp.png
  app/src/main/res/drawable/ic_isfj.png
  app/src/main/res/drawable/ic_isfp.png
  app/src/main/res/drawable/ic_istj.png
  app/src/main/res/drawable/ic_istp.png
  app/src/main/res/drawable/ic_photosize.xml
  app/src/main/res/drawable/ic_post_like_off.png
  app/src/main/res/drawable/ic_post_like_on.png
  app/src/main/res/drawable/ic_search_post.xml
  app/src/main/res/drawable/ic_search_post_btn_off.png
  app/src/main/res/drawable/ic_search_post_btn_on.png
  app/src/main/res/drawable/mbti_quest_disabled_btn.xml
  app/src/main/res/drawable/mbti_quest_enabled_btn.xml
  app/src/main/res/drawable/post_like_select_btn.xml
  app/src/main/res/drawable/post_search_background.xml
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_mbti_quest.xml
  app/src/main/res/layout/activity_mbti_result.xml
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/activity_post_item.xml
  app/src/main/res/layout/activity_post_list.xml
  app/src/main/res/layout/activity_post_write.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/mbti_dialog_choice.xml
Labels: UI, FEAT, FIX

#95 UserList / Myprofile
  app/src/main/java/com/example/mbti_talk/Adapter/UserAdapter.kt
  app/src/main/res/drawable/detail_man_kit.xml
  app/src/main/res/drawable/detail_woman_kit.xml
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/layout/user_list.xml
Labels: UI, FIX

#99 필터 기능에 남녀 둘다 선택 기능 추가
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/java/com/example/mbti_talk/Main/FilterDialogFragment.kt
  app/src/main/res/drawable/chip_selected_man.xml
  app/src/main/res/drawable/chip_selected_woman.xml
  app/src/main/res/drawable/detail_default_kit.xml
  app/src/main/res/layout/fragment_dialog_filter.xml
Labels: FIX

#100 mipmap-icon, postFragment-page
  app/src/main/AndroidManifest.xml
  app/src/main/ic_mbti_talk-playstore.png
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
  app/src/main/java/com/example/mbti_talk/post/PostAdapter.kt
  app/src/main/java/com/example/mbti_talk/post/PostDetailActivity.kt
  app/src/main/java/com/example/mbti_talk/post/PostFragment.kt
  app/src/main/java/com/example/mbti_talk/post/PostLikeActivity.kt
  app/src/main/java/com/example/mbti_talk/post/PostWriteActivity.kt
  app/src/main/res/drawable/ic_arrow_down.png
  app/src/main/res/drawable/ic_arrow_down_size.xml
  app/src/main/res/drawable/ic_mbti_talk_background.xml
  app/src/main/res/drawable/post_spinner_design.xml
  app/src/main/res/drawable/splash_image.png
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/activity_post_item.xml
  app/src/main/res/layout/activity_post_like_list.xml
  app/src/main/res/layout/activity_post_list.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/custom_spinner_item.xml
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/mipmap-anydpi-v26/ic_mbti_talk.xml
  app/src/main/res/mipmap-anydpi-v26/ic_mbti_talk_round.xml
  app/src/main/res/mipmap-hdpi/ic_mbti_talk.webp
  app/src/main/res/mipmap-hdpi/ic_mbti_talk_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_mbti_talk_round.webp
  app/src/main/res/mipmap-mdpi/ic_mbti_talk.webp
  app/src/main/res/mipmap-mdpi/ic_mbti_talk_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_mbti_talk_round.webp
  app/src/main/res/mipmap-xhdpi/ic_mbti_talk.webp
  app/src/main/res/mipmap-xhdpi/ic_mbti_talk_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_mbti_talk_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_mbti_talk.webp
  app/src/main/res/mipmap-xxhdpi/ic_mbti_talk_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_mbti_talk_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_mbti_talk.webp
  app/src/main/res/mipmap-xxxhdpi/ic_mbti_talk_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_mbti_talk_round.webp
  app/src/main/res/values/ic_mbti_talk_background.xml
  app/src/main/res/values/string-array.xml
  app/src/main/res/values/strings.xml
Labels: UI, FEAT

#102 Feat/doyeon
  app/src/main/java/com/example/mbti_talk/Main/FilterDialogFragment.kt
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
  app/src/main/res/layout/fragment_dialog_filter.xml
  app/src/main/res/values/colors.xml
Labels: FIX

#103 App icon
  app/src/main/ic_mbti_talk-playstore.png
  app/src/main/res/drawable/post_search_background.xml
  app/src/main/res/drawable/post_spinner_design.xml
  app/src/main/res/drawable/splash_image.png
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/layout/mbti_dialog_choice.xml
  app/src/main/res/mipmap-hdpi/ic_mbti_talk.webp
  app/src/main/res/mipmap-hdpi/ic_mbti_talk_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_mbti_talk_round.webp
  app/src/main/res/mipmap-mdpi/ic_mbti_talk.webp
  app/src/main/res/mipmap-mdpi/ic_mbti_talk_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_mbti_talk_round.webp
  app/src/main/res/mipmap-xhdpi/ic_mbti_talk.webp
  app/src/main/res/mipmap-xhdpi/ic_mbti_talk_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_mbti_talk_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_mbti_talk.webp
  app/src/main/res/mipmap-xxhdpi/ic_mbti_talk_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_mbti_talk_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_mbti_talk.webp
  app/src/main/res/mipmap-xxxhdpi/ic_mbti_talk_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_mbti_talk_round.webp
  app/src/main/res/values/strings.xml
Labels: UI

#104 Feat/doyeon
  app/src/main/java/com/example/mbti_talk/Main/FilterDialogFragment.kt
  app/src/main/res/layout/fragment_dialog_filter.xml
Labels: FIX

#105 MyprofileFragment-page
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
  app/src/main/java/com/example/mbti_talk/MyProfile/SignoutDialogChoice.kt
  app/src/main/res/layout/fragment_my_profile.xml
Labels: FEAT

#107 FriendlistFragment-page
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/mbti_talk/FriendList/FriendListFragment.kt
  app/src/main/res/drawable/img_nofriend.png
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_friend_find.xml
  app/src/main/res/layout/fragment_friend_list.xml
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/layout/list_chatroom_item.xml
  app/src/main/res/layout/list_talk_item_mine.xml
  app/src/main/res/layout/list_talk_item_others.xml
Labels: UI, FEAT, FIX

#108 All Fragment - page
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/post/PostWriteActivity.kt
  app/src/main/res/drawable/ic_mbti_search_btn.png
  app/src/main/res/drawable/ic_mbti_search_btn_on.png
  app/src/main/res/drawable/myprofile_mbti_btn.xml
  app/src/main/res/layout/activity_post_list.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/dialog_forgot.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_friend_find.xml
  app/src/main/res/layout/fragment_friend_list.xml
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/values/themes.xml
  wavybottomnavigation/src/main/res/values/colors.xml
Labels: UI, FEAT

#109 FilterDialogFragment
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/java/com/example/mbti_talk/Main/FilterDialogFragment.kt
  app/src/main/java/com/example/mbti_talk/Main/GraphMbtiFragment.kt
  app/src/main/res/drawable/filter1.xml
  app/src/main/res/drawable/filter2.xml
  app/src/main/res/drawable/filter_btn1.xml
  app/src/main/res/drawable/filter_check.xml
  app/src/main/res/drawable/filter_icon.png
  app/src/main/res/drawable/filter_normal.xml
  app/src/main/res/drawable/ic_checkmark.png
  app/src/main/res/drawable/img_logo.png
  app/src/main/res/drawable/mbti_graph.png
  app/src/main/res/drawable/mbti_logo.png
  app/src/main/res/drawable/selector_btn.xml
  app/src/main/res/layout/fragment_dialog_filter.xml
  app/src/main/res/layout/fragment_friend_find.xml
  app/src/main/res/layout/fragment_mbti_graph.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: bug, UI, FEAT

#110 FriendFindFragment
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/java/com/example/mbti_talk/Main/FilterDialogFragment.kt
  app/src/main/java/com/example/mbti_talk/utils/Utils.kt
  app/src/main/res/drawable/background_filter.xml
  app/src/main/res/drawable/filter_btn1.xml
  app/src/main/res/layout/fragment_friend_find.xml
Labels: UI, FEAT

#111 signup,signup2,myprofile-page
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/SignUpActivity.kt
  app/src/main/java/com/example/mbti_talk/SignUpActivity2.kt
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/fragment_my_profile.xml
Labels: UI, FEAT, FIX

#113 유저 중복 문제 해결
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/fragment_friend_list.xml
Labels: bug

#114 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/values/themes.xml
Labels: FEAT

#115 dialog rangebar 버그 수정
  app/build.gradle.kts
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/res/drawable/img_filtered_nofriend.png
  app/src/main/res/layout/fragment_friend_find.xml
  app/src/main/res/values/themes.xml
Labels: bug

#116 MyProfileFragment-page
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
Labels: bug, FIX

#119 DetailActivity (특정 사용자 차단 버튼 클릭 시 해당 사용자와 대화한 채팅방 삭제)
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/java/com/example/mbti_talk/FriendBlockActivity.kt
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/res/layout/activity_friend_block.xml
  app/src/main/res/layout/fragment_friend_find.xml
Labels: FEAT

#121 GraphMbtiFragment 줌인기능 추가
  app/src/main/java/com/example/mbti_talk/Main/GraphMbtiFragment.kt
  app/src/main/res/layout/fragment_mbti_graph.xml
Labels: FEAT

#124 차단당한 상태에서 채팅금지 기능 구현
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/java/com/example/mbti_talk/Main/MbtiDialogFragment.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/fragment_mbti_dialog.xml
Labels: FEAT

#127 example.com 패키지 변경, 구글서비스관련 수정
  app/google-services.json
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/res/values/strings.xml
Labels: bug

#128 UI/blockdialog
  app/src/main/java/com/example/mbti_talk/Dialog_unblockCheckFragment.kt
  app/src/main/java/com/example/mbti_talk/FriendBlockActivity.kt
  app/src/main/res/layout/dialog_block_check.xml
  app/src/main/res/layout/dialog_unblock_check.xml
  app/src/main/res/layout/fragment_dialog_unblock_check.xml
Labels: UI, FEAT

#129 xml 수정 밑 메인 화면 리사이클러뷰 재사용 오류 수정
  app/src/main/java/com/example/mbti_talk/Adapter/UserAdapter.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_friend_find.xml
Labels: FEAT, FIX

#117 ChatFragment-page
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/mbti_talk/Chat/ChatFragment.kt
  app/src/main/java/com/example/mbti_talk/Chat/RecyclerChatRoomsAdapter.kt
  app/src/main/res/drawable/img_nochat.png
  app/src/main/res/layout/fragment_chat.xml
Labels: UI

#130 profile-page
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
  app/src/main/res/layout/fragment_my_profile.xml
Labels: FEAT

#131 [BUG_FIX] Age textview 만 보여지지 않는 버그 해결
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  gradlew
Labels: FIX

#133 수정/ 삭제
  app/src/main/java/com/example/mbti_talk/post/PostAdapter.kt
  app/src/main/java/com/example/mbti_talk/post/PostMyDetailActivity.kt
  app/src/main/java/com/example/mbti_talk/post/PostWriteActivity.kt
  app/src/main/res/layout/dialog_post_detail.xml
Labels: FEAT

#135 수정
  app/src/main/res/layout/fragment_my_profile.xml
Labels: FIX

#136 Feature/mbti2
  app/src/main/java/com/example/mbti_talk/post/PostMyDetailActivity.kt
  app/src/main/java/com/example/mbti_talk/post/PostWriteActivity.kt
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/activity_post_my_detail.xml
Labels: FEAT

#138 PostMyDetailActivity.kt 수정 기능 완료
  app/src/main/java/com/example/mbti_talk/post/PostWriteActivity.kt
Labels: FEAT

#139 바텀에 포함된 모든 Fragment -page
  app/build.gradle.kts
  app/src/main/java/com/example/mbti_talk/Chat/ChatFragment.kt
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/java/com/example/mbti_talk/FriendList/FriendListFragment.kt
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
  app/src/main/java/com/example/mbti_talk/post/PostFragment.kt
  app/src/main/java/com/example/mbti_talk/post/PostWriteActivity.kt
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_post_list.xml
  app/src/main/res/layout/activity_post_write.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_friend_find.xml
  app/src/main/res/layout/fragment_friend_list.xml
  app/src/main/res/layout/fragment_my_profile.xml
Labels: FEAT

#140 PostMyDetailActivity-page
  app/src/main/java/com/example/mbti_talk/post/PostWriteActivity.kt
Labels: FIX

#143 톡 완료
  app/src/main/AndroidManifest.xml
Labels: FIX

#144 [DESIGN] 다이얼로그 textview 정렬 바르게
  app/src/main/res/layout/fragment_dialog_filter.xml
  app/src/main/res/values/styles.xml
Labels: UI

#145 M친톡 완성본
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_sign_up2.xml
Labels: FEAT

#147 M친톡 완성본 찐 완성본
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
Labels: FEAT

#150 signUpActivity-page
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_sign_up2.xml
Labels: FIX

#152 6 버전 업데이트
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/SplashActivity.kt
  app/src/main/java/com/example/mbti_talk/post/PostAdapter.kt
  app/src/main/res/layout/dialog_post_detail.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: FIX

#154 [BUG_FIX] 친추 버튼 클릭해도 버튼 안사라짐 문제 해결
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
Labels: FIX

#155 [BUG_FIX] 뒤로가기 클릭 시, 토스팅 메세지
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/java/com/example/mbti_talk/Main/BottomActivity.kt
  app/src/main/res/layout/activity_log_in.xml
Labels: FEAT

#157 little bug 수정
  app/src/main/java/com/example/mbti_talk/SignUpActivity.kt
  app/src/main/res/layout/activity_sign_up.xml
Labels: bug, FIX
