Repository 6pleasant-MBTITalk/MBTI_Talk, pull requests merged in 2023-10, with the labels that each got.

#3 Feature/signup
  .idea/misc.xml
  app/build.gradle.kts
  app/google-services.json
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/SignUpActivity.kt
  app/src/main/res/layout/activity_log_in.xml
  build.gradle.kts
Labels: FEAT

#4 manifest 수정
  .idea/.name
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
Labels: FIX

#5 [FEAT] : ⚙️ [BUG_FIX] : 🐛 SignUpActivity.kt FireBase에 데이터 넣기, 아이디, 비밀…
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/SignUpActivity.kt
  app/src/main/java/com/example/mbti_talk/UserData.kt
Labels: FEAT

#6 Feature/login
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/Porfile.kt
  app/src/main/java/com/example/mbti_talk/SignUpActivity.kt
  app/src/main/res/layout/activity_profile.xml
  build.gradle.kts
Labels: FEAT

#8 [FEAT] : ⚙️Database_Read(데이터 읽어오기)
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/Porfile.kt
Labels: FEAT

#9 [FEAT] : ⚙️ 회원가입 넘어가기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/SignUpActivity.kt
Labels: FEAT

#10 [FEAT]⚙️ 회원가입정보 인텐트로 넘기기
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/Porfile.kt
  app/src/main/java/com/example/mbti_talk/SignUpActivity.kt
Labels: FEAT

#11 [Little_FIX]🔧️오타수정~
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/Profile.kt
  app/src/main/res/layout/activity_profile.xml
Labels: FEAT

#13 [DESIGN] : 🎨 design/login_dialog
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/mbti_talk/SignupDialogFragment.kt
  app/src/main/res/layout/dialog_forgot.xml
  app/src/main/res/layout/dialog_signup.xml
Labels: UI

#14 Feature/post1
  app/build.gradle.kts
  app/src/main/res/drawable/mbti_search_btn.xml
  app/src/main/res/drawable/mbti_selecbox_btn.xml
  app/src/main/res/drawable/mbti_txt_title.xml
  app/src/main/res/drawable/mbti_vline_kit.xml
  app/src/main/res/layout/activity_mbti_input.xml
  app/src/main/res/layout/activity_mbti_selectionbox.xml
  app/src/main/res/values/colors.xml
Labels: UI, FEAT

#16 [Features/Chat]⚙️채팅 기능만추가(상세 intetn및기능 구현 필요)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/Chat/ChatActivity.kt
  app/src/main/java/com/example/mbti_talk/Chat/Message.kt
  app/src/main/java/com/example/mbti_talk/Chat/MessageAdapter.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/receive_message.xml
  app/src/main/res/layout/send_message.xml
Labels: FEAT

#17 [Fix]🔧 로그인 회원가입초기화
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/SignUpActivity.kt
Labels: FIX

#19 UI/login
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/java/com/example/mbti_talk/utils/Utils.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_profile.xml
Labels: UI, FEAT

#20 Feature/mbti12
  app/src/main/java/com/example/mbti_talk/Profile.kt
  app/src/main/java/com/example/mbti_talk/SelectionMbtiActivity.kt
  app/src/main/java/com/example/mbti_talk/SignUpMbtiActivity.kt
  app/src/main/res/drawable/mbti_selecbox_btn.xml
  app/src/main/res/drawable/mbti_selecbox_leftbtn.xml
  app/src/main/res/drawable/mbti_selecbox_rightbtn.xml
  app/src/main/res/layout/activity_mbti_input.xml
  app/src/main/res/layout/activity_mbti_selectionbox.xml
  app/src/main/res/layout/activity_profile.xml
Labels: FEAT

#21 [FEAT] : ⚙️ SignUpMbtiActivity.kt 입력 받은 값을 가지고 설명을 해준다.
  app/src/main/java/com/example/mbti_talk/SignUpMbtiActivity.kt
  app/src/main/res/layout/activity_mbti_input.xml
Labels: FEAT

#22 Feature/mbti2
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/PostWriteActivity.kt
  app/src/main/res/drawable/ic_photo.png
  app/src/main/res/drawable/post_image_border.xml
  app/src/main/res/drawable/post_title_line.xml
  app/src/main/res/layout/activity_post_write.xml
Labels: UI, FEAT

#24 [LITTLE_FIX] : 🔧 littlefix/signup 라디오버튼 클릭 시 남/여 넘기기
  app/src/main/java/com/example/mbti_talk/Adapter/FriendAdapter.kt
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/java/com/example/mbti_talk/SignUpActivity.kt
  app/src/main/java/com/example/mbti_talk/UserData.kt
  app/src/main/res/layout/activity_sign_up.xml
Labels: FIX

#27 UI/user detail
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/items/PostItemActivity.kt
  app/src/main/res/drawable/content_img_radius_kit.xml
  app/src/main/res/drawable/detail_man_kit.xml
  app/src/main/res/drawable/detail_woman_kit.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_post_item.xml
  app/src/main/res/layout/activity_profile.xml
Labels: UI, FIX

#28 [feat]utils fix
  app/src/main/java/com/example/mbti_talk/utils/Utils.kt
Labels: FEAT, FIX

#29 [FEAT] : ⚙️ feature/fbgooglelogin 구글로그인 기능 추가
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/SignUpActivity.kt
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/values/strings.xml
Labels: FEAT

#30 Feat/doyeon
  app/src/main/java/com/example/mbti_talk/Adapter/UserAdapter.kt
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/res/layout/activity_detail.xml
Labels: FEAT

#31 Feature/mbti2
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/PostWriteActivity.kt
  app/src/main/java/com/example/mbti_talk/SignUpMbtiActivity.kt
  app/src/main/java/com/example/mbti_talk/items/PostItemActivity.kt
  app/src/main/java/com/example/mbti_talk/post/FirebaseData.kt
  app/src/main/java/com/example/mbti_talk/post/PostActivity.kt
  app/src/main/java/com/example/mbti_talk/post/PostAdapter.kt
  app/src/main/java/com/example/mbti_talk/post/PostWriteActivity.kt
  app/src/main/res/drawable/ic_add.png
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_post_item.xml
  app/src/main/res/layout/activity_post_list.xml
Labels: FEAT

#40 UI/user detail
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/Chat/ChatFragment.kt
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/java/com/example/mbti_talk/FriendList/FriendListFragment.kt
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/Main/BottomActivity.kt
  app/src/main/java/com/example/mbti_talk/Main/MainActivity.kt
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
  app/src/main/java/com/example/mbti_talk/SignUpMbtiActivity.kt
  app/src/main/res/layout/activity_bottom.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/fragment_friend_find.xml
  app/src/main/res/layout/fragment_friend_list.xml
  app/src/main/res/layout/fragment_my_profile.xml
  app/src/main/res/layout/fragment_post.xml
  app/src/main/res/menu/navi_menu.xml
Labels: UI, FEAT, FIX

#44 Feature/mbti2
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/TestActivity.kt
  app/src/main/java/com/example/mbti_talk/post/PostAdapter.kt
  app/src/main/java/com/example/mbti_talk/post/PostFragment.kt
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_test.xml
  app/src/main/res/layout/fragment_post.xml
Labels: FEAT

#49 Feat/bot nav
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/Adapter/FriendAdapter.kt
  app/src/main/java/com/example/mbti_talk/Adapter/UserAdapter.kt
  app/src/main/java/com/example/mbti_talk/Main/BottomActivity.kt
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
  app/src/main/java/com/example/mbti_talk/Profile.kt
  app/src/main/java/com/example/mbti_talk/post/PostDetailActivity.kt
  app/src/main/res/layout/activity_bottom.xml
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/menu/navi_menu.xml
Labels: UI, FEAT, FIX

#50 Feature/mbti2
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/mbti_talk/post/PostAdapter.kt
  app/src/main/java/com/example/mbti_talk/post/PostFragment.kt
Labels: FEAT

#57 [FEAT]Features/chat 채팅추가
  app/src/main/java/com/example/mbti_talk/Chat/ChatActivity.kt
  app/src/main/java/com/example/mbti_talk/Chat/ChatFragment.kt
  app/src/main/java/com/example/mbti_talk/Chat/ChatRoom.kt
  app/src/main/java/com/example/mbti_talk/Chat/ChatRoomActivity.kt
  app/src/main/java/com/example/mbti_talk/Chat/Message.kt
  app/src/main/java/com/example/mbti_talk/Chat/MessageAdapter.kt
  app/src/main/java/com/example/mbti_talk/Chat/RecyclerChatRoomsAdapter.kt
  app/src/main/java/com/example/mbti_talk/Chat/RecyclerMessagesAdapter.kt
  app/src/main/java/com/example/mbti_talk/Chat/User.kt
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/res/drawable/background_talk_mine.xml
  app/src/main/res/drawable/background_talk_others.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_chat_room.xml
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/layout/list_chatroom_item.xml
  app/src/main/res/layout/list_talk_item_mine.xml
  app/src/main/res/layout/list_talk_item_others.xml
  app/src/main/res/layout/receive_message.xml
  app/src/main/res/layout/send_message.xml
Labels: FEAT

#58 [FEAT] Feature/mbti2
  app/src/main/java/com/example/mbti_talk/post/PostAdapter.kt
  app/src/main/java/com/example/mbti_talk/post/PostDetailActivity.kt
  app/src/main/java/com/example/mbti_talk/post/PostFragment.kt
  app/src/main/java/com/example/mbti_talk/post/PostWriteActivity.kt
  app/src/main/res/drawable/ic_add.png
  app/src/main/res/drawable/ic_add_plus.png
  app/src/main/res/layout/activity_main_friend.xml
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/activity_post_item.xml
  app/src/main/res/layout/activity_post_list.xml
  app/src/main/res/layout/activity_post_write.xml
Labels: FEAT

#60 UI/bot nav
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/java/com/example/mbti_talk/Main/BottomActivity.kt
  app/src/main/java/com/example/mbti_talk/utils/Utils.kt
  app/src/main/res/drawable/ic_account.xml
  app/src/main/res/drawable/ic_explore.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_message.xml
  app/src/main/res/drawable/ic_notification.xml
  app/src/main/res/layout/activity_bottom.xml
  settings.gradle.kts
  wavybottomnavigation/.gitignore
  wavybottomnavigation/build.gradle
  wavybottomnavigation/consumer-rules.pro
  wavybottomnavigation/proguard-rules.pro
  wavybottomnavigation/src/androidTest/java/com/tauheed/wavybottomnavigation/ExampleInstrumentedTest.kt
  wavybottomnavigation/src/main/AndroidManifest.xml
  wavybottomnavigation/src/main/assets/fonts/SourceSansPro-Regular.ttf
  wavybottomnavigation/src/main/assets/fonts/SourceSansPro-SemiBold.ttf
  wavybottomnavigation/src/main/java/com/tauheed/wavybottomnavigation/Utils.kt
  wavybottomnavigation/src/main/java/com/tauheed/wavybottomnavigation/WavyBottomNavigation.kt
  wavybottomnavigation/src/main/java/com/tauheed/wavybottomnavigation/WavyBottomNavigationCell.kt
  wavybottomnavigation/src/main/java/com/tauheed/wavybottomnavigation/WavyView.kt
  wavybottomnavigation/src/main/res/layout/wavy_navigation_cell.xml
  wavybottomnavigation/src/main/res/values/colors.xml
  wavybottomnavigation/src/main/res/values/strings.xml
  wavybottomnavigation/src/test/java/com/tauheed/wavybottomnavigation/ExampleUnitTest.kt
Labels: UI, FEAT

#62 [STYLE] feat/doyeon
  app/src/main/java/com/example/mbti_talk/Adapter/UserAdapter.kt
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/java/com/example/mbti_talk/Main/MainActivity.kt
Labels: FIX

#64 [FEAT] Feature/mbti2 PostFragment 외 다른 페이지 디자인 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mbti_talk/DetailActivity.kt
  app/src/main/java/com/example/mbti_talk/FriendFind/FriendFindFragment.kt
  app/src/main/java/com/example/mbti_talk/FriendList/FriendListFragment.kt
  app/src/main/java/com/example/mbti_talk/LogInActivity.kt
  app/src/main/java/com/example/mbti_talk/MBTI/MbtiActivity.kt
  app/src/main/java/com/example/mbti_talk/MBTI/SignUpMbtiActivity.kt
  app/src/main/java/com/example/mbti_talk/Main/BottomActivity.kt
  app/src/main/java/com/example/mbti_talk/MyProfile/MyProfileFragment.kt
  app/src/main/res/drawable/ic_down_arrow.png
  app/src/main/res/layout/activity_mbti_selectionbox.xml
  app/src/main/res/layout/activity_post_detail.xml
  app/src/main/res/layout/activity_post_item.xml
  app/src/main/res/layout/activity_post_list.xml
  app/src/main/res/layout/activity_post_my_detail.xml
Labels: FEAT, FIX

#67 bottom_navigation
  .idea/.name
  app/src/main/java/com/example/mbti_talk/Main/BottomActivity.kt
  app/src/main/res/layout/activity_bottom.xml
  app/src/main/res/layout/fragment_friend_list.xml
Labels: UI, FEAT, FIX
